name: eform_modul
description: A new Flutter module project.
publish_to : 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13

  # A powerful Http client for Dart, which supports Interceptors,
  # Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.
  dio: 4.0.0

  # State Management, Widgets that make it easy to integrate blocs and cubits into Flutter.
  # Built to work with package:bloc.
#  flutter_bloc: ^8.0.1

  get: ^4.6.1

  # This is a simple Service Locator for Dart and Flutter projects with some additional goodies highly inspired by Splat.
  # It can be used instead of InheritedWidget or Provider to access objects e.g. from your UI.
  get_it: ^7.1.3

  # Provides super simple APIs for logging.
  # The log also includes caller info by setting includeCallerInfo to true. On Android Studio,
  # jump to caller info by clicking the log.
  simple_logger: ^1.8.0+1

  # Provides internationalization and localization facilities, including message translation,
  # plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0

  # Draw SVG (and some Android VectorDrawable (XML)) files on a Flutter Widget.
  flutter_svg: ^0.23.0+1

  # Being able to compare objects in Dart often involves having to override the == operator as well as hashCode
  equatable: ^2.0.2

  # A Flutter widget that scrolls text infinitely. Provides many customizations including custom scroll directions,
  # durations, curves as well as pauses after every round.
  marquee: ^2.1.0

  # A Plugin Library for carousel slider widget.
  carousel_slider: ^4.0.0

  # A plugin for kekeureudeupan widget
  shimmer: ^2.0.0

  # A Flutter plugin for launching a URL. Supports iOS, Android, web, Windows, macOS, and Linux.
  url_launcher: 6.0.5

  # A Flutter plugin for iOS and Android for picking images from the image library,
  # and taking new pictures with the camera.
  image_picker: ^0.8.0

  # A Flutter plugin for Android and iOS supports cropping images. This plugin is based on two different native libraries
  # so it comes with different UI between these platforms
  # image_cropper: ^1.4.0

  # Get current device information from within the Flutter application.
  device_info_plus: 2.1.0

  # plugin for info IP ADRESS
  dart_ipify: 1.1.0

  # Package designed to select an item from a list, with the option to filter and even search the items online
  select_dialog: ^2.0.0

  # An elastic material bottom sheet implementation for Flutter.
  # rubber: ^1.0.0

  flutter_html: ^2.2.1
  google_fonts: ^2.3.1
  pdf: ^3.7.2
  flutter_downloader: ^1.7.3
  flutter_launcher_icons: "^0.9.2"

  geolocator: ^8.2.0
  # flutter_geocoder:
  #   git:
  #     url: https://github.com/JCKodel/flutter_geocoder.git
  #     ref: "7059f6f"
  # geocode: ^1.0.1
  geocoding: ^2.0.4


  camera: ^0.9.4+16

  dotted_border: ^2.0.0

  flutter_active_passive_liveness:
    git:
      url: https://gitlab+deploy-token-742801:tqDsceacRyyPBCK38oms@gitlab.com/oxycreative/flutter-packages/active-passive-liveness.git
      ref: v2.0.2-encrypted-prod


  intl_phone_number_input: ^0.7.0+2
  string_validator: ^0.3.0
  # tflite_flutter: ^0.9.0
  # tflite_flutter_helper: ^0.3.1
  pin_code_fields: ^7.3.0
  xml2json: ^5.3.2
  open_file: ^3.2.1
  syncfusion_flutter_pdf: ^19.4.56-beta
  path_provider: ^2.0.9
  # image_gallery_saver: ^1.7.1
  permission_handler: ^9.2.0
  encrypt: ^5.0.1
  pointycastle: ^3.5.0
  flutter_easyloading: ^3.0.3
  sizer: ^2.0.15
  downloads_path_provider_28: ^0.1.2
  flutter_exif_rotation: ^0.5.1
  connectivity_plus: ^2.2.2
  isolate_image_compress: ^1.0.0
  store_redirect: ^2.0.1
  external_app_launcher: ^2.0.2
  # jwtson: ^1.0.7
  # Package jwt untuk di testing
  # jwtson:
  #   git:
  #     url: https://gitlab+deploy-token-3:v8vuFV6a-p53EN56xYzE@gitlab.bni.co.id/bbc/flutter-package/jwtson.git
  #     ref : Development
  jwtson:
    git:
      url: https://gitlab+deploy-token-3:sG5LJSyWhCAuv5k5Dqbd@code.digi46.id/eformdigi46/flutter-package/jwtson.git
      ref : jwtson
  # device_platform_info: ^1.0.0
  google_mlkit_face_detection: ^0.3.0

  # Package encrypt rsa untuk di testing
  # encryptrsa:
  #   git:
  #     url: https://gitlab+deploy-token-5:QUyvX-LAmZX8L5FYCxb2@gitlab.bni.co.id/bbc/flutter-package/loadkeyencryptpin-libc.git
  #     ref : Development
  encryptrsa:
    git:
      url: https://gitlab+deploy-token-5:zxzHmwJvNt5G3XziR9YS@code.digi46.id/eformdigi46/flutter-package/loadkeyencryptpin-libc.git
      ref : 0.0.1
  # Package device info untuk di testing
  device_info:
    git:
      url: https://gitlab+deploy-token-4:r2ZJ-uSdsfxjnTNYbFAB@code.digi46.id/eformdigi46/flutter-package/deviceinfo.git
      ref : 0.0.1
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  assets:
    - assets/images/
    - assets/jsonfiles/
    - assets/tflite/
    - assets/images/icons/
    - assets/images/bendera/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: bbc.u46.eform_modul
    iosBundleIdentifier: bbc.u46.eformModul
